"""Declarative calibration metadata for the eight calibrated dimensions."""

DIMENSION_LABELS = {
    "academic_base": "学业基础表现",
    "class_engagement": "课堂学习投入",
    "online_activeness": "在线学习积极性",
    "library_immersion": "图书馆沉浸度",
    "network_habits": "网络作息自律指数",
    "daily_routine_boundary": "早晚生活作息规律",
    "physical_resilience": "体质及运动状况",
    "appraisal_status_alert": "综合荣誉与异动预警",
}

LEVEL_LABELS = {
    "high": "高",
    "medium": "中",
    "low": "低",
}

THRESHOLD_STRATEGY_METADATA = {
    "fixed": {
        "description": "Use frozen score cutoffs for stable business rules.",
        "distribution_sensitive": False,
    },
    "quantile": {
        "description": "Use cohort quantiles when relative ranking is needed.",
        "distribution_sensitive": True,
    },
    "hybrid": {
        "description": "Blend fixed cutoffs with cohort context for mixed signals.",
        "distribution_sensitive": True,
    },
}

CALIBRATED_DIMENSIONS = [
    "academic_base",
    "class_engagement",
    "online_activeness",
    "library_immersion",
    "network_habits",
    "daily_routine_boundary",
    "physical_resilience",
    "appraisal_status_alert",
]


def _rule(
    dimension_code: str,
    metric: str,
    display_name: str,
    raw_fields: list[str],
    threshold_strategy: str,
    *,
    influence_direction: str,
    aggregation: str,
    evidence_label: str,
    deferred_status: dict[str, object] | None = None,
    caveat: str | None = None,
    evidence_role: str = "primary",
) -> dict[str, object]:
    rule = {
        "dimension_code": dimension_code,
        "dimension_label": DIMENSION_LABELS[dimension_code],
        "metric": metric,
        "display_name": display_name,
        "evidence_label": evidence_label,
        "raw_fields": raw_fields,
        "threshold_strategy": threshold_strategy,
        "influence_direction": influence_direction,
        "aggregation": aggregation,
        "deferred_status": deferred_status or {"state": "none"},
        "evidence_role": evidence_role,
    }
    if caveat is not None:
        rule["caveat"] = caveat
    return rule


METRIC_RULE_DECLARATIONS = {
    "academic_base": [
        _rule(
            "academic_base",
            "term_gpa",
            "学期GPA",
            ["JDCJ", "XF"],
            "fixed",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="学期GPA",
        ),
        _rule(
            "academic_base",
            "failed_course_count",
            "挂科门数",
            ["KCCJ", "DJCJ", "KSLXDM"],
            "fixed",
            influence_direction="negative",
            aggregation="count_lt_60",
            evidence_label="挂科门数",
        ),
        _rule(
            "academic_base",
            "borderline_course_count",
            "边缘课程数",
            ["KCCJ", "DJCJ"],
            "fixed",
            influence_direction="negative",
            aggregation="count_60_to_69",
            evidence_label="边缘课程数",
        ),
        _rule(
            "academic_base",
            "failed_course_ratio",
            "挂科占比",
            ["KCCJ", "DJCJ", "KSLXDM"],
            "fixed",
            influence_direction="negative",
            aggregation="derived_ratio",
            evidence_label="挂科占比",
        ),
    ],
    "class_engagement": [
        _rule(
            "class_engagement",
            "attendance_rate",
            "出勤率",
            ["ZTDM", "ZT", "DKSJ"],
            "fixed",
            influence_direction="positive",
            aggregation="ratio",
            evidence_label="出勤率",
            deferred_status={
                "state": "caveated",
                "condition": "student_linkage_proven_for_attention_metrics",
                "fallback": "attendance_derived_only",
            },
            caveat="课堂注意力指标在学生链接未证明前暂缓，先使用出勤衍生指标。",
        ),
        _rule(
            "class_engagement",
            "late_count",
            "迟到次数",
            ["ZTDM", "ZT", "DKSJ"],
            "fixed",
            influence_direction="negative",
            aggregation="count",
            evidence_label="迟到次数",
        ),
        _rule(
            "class_engagement",
            "truancy_count",
            "旷课次数",
            ["ZTDM", "ZT", "DKSJ"],
            "fixed",
            influence_direction="negative",
            aggregation="count",
            evidence_label="旷课次数",
        ),
        _rule(
            "class_engagement",
            "absence_count",
            "缺勤次数",
            ["ZTDM", "ZT", "DKSJ"],
            "fixed",
            influence_direction="negative",
            aggregation="count",
            evidence_label="缺勤次数",
        ),
    ],
    "online_activeness": [
        _rule(
            "online_activeness",
            "video_completion_rate",
            "视频完成率",
            ["VIDEOJOB_RATE"],
            "fixed",
            influence_direction="positive",
            aggregation="ratio",
            evidence_label="视频完成率",
            deferred_status={
                "state": "caveated",
                "condition": "login_name_to_student_id_crosswalk_required",
                "fallback": "delay_until_linked",
            },
            caveat="学生级在线学习指标依赖 LOGIN_NAME -> student_id 映射；未建立时保持延后而不推断。",
        ),
        _rule(
            "online_activeness",
            "online_test_avg_score",
            "测验均分",
            ["TEST_AVGSCORE"],
            "fixed",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="测验均分",
        ),
        _rule(
            "online_activeness",
            "online_work_avg_score",
            "作业均分",
            ["WORK_AVGSCORE"],
            "fixed",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="作业均分",
        ),
        _rule(
            "online_activeness",
            "online_exam_avg_score",
            "考试均分",
            ["EXAM_AVGSCORE"],
            "fixed",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="考试均分",
        ),
        _rule(
            "online_activeness",
            "platform_engagement_score",
            "平台活跃度",
            ["BFB"],
            "quantile",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="平台活跃度",
        ),
        _rule(
            "online_activeness",
            "forum_interaction_total",
            "论坛互动总量",
            ["BBS_NUM", "TOPIC_NUM", "REPLY_NUM"],
            "quantile",
            influence_direction="positive",
            aggregation="sum",
            evidence_label="论坛互动总量",
            evidence_role="support",
        ),
    ],
    "library_immersion": [
        _rule(
            "library_immersion",
            "library_completed_visit_count",
            "入馆次数",
            ["visittime", "direction", "gateno"],
            "hybrid",
            influence_direction="positive",
            aggregation="count",
            evidence_label="入馆次数",
        ),
        _rule(
            "library_immersion",
            "avg_library_stay_minutes",
            "平均停留时长",
            ["visittime", "direction"],
            "fixed",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="平均停留时长",
            deferred_status={
                "state": "caveated",
                "condition": "in_out_pairing_required",
                "fallback": "visit_count_only",
            },
            caveat="停留时长依赖完整进出配对；配对不完整时只保留入馆次数。",
        ),
        _rule(
            "library_immersion",
            "weekly_library_visit_avg",
            "周均入馆次数",
            ["visittime"],
            "hybrid",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="周均入馆次数",
        ),
    ],
    "network_habits": [
        _rule(
            "network_habits",
            "monthly_online_duration_avg",
            "月均上网时长",
            ["SWLJSC"],
            "hybrid",
            influence_direction="negative",
            aggregation="mean",
            evidence_label="月均上网时长",
            deferred_status={
                "state": "caveated",
                "condition": "deep_night_metrics_blocked",
                "fallback": "aggregate_usage_only",
            },
            caveat="不声称深夜指标，不使用 0:00-6:00 明细；仅允许聚合上网强度。",
        ),
        _rule(
            "network_habits",
            "term_online_duration_sum",
            "学期总上网时长",
            ["SWLJSC", "TJNY", "XN", "XQ"],
            "hybrid",
            influence_direction="negative",
            aggregation="sum",
            evidence_label="学期总上网时长",
        ),
        _rule(
            "network_habits",
            "online_duration_vs_school_avg_gap",
            "相对学校平均值偏差",
            ["SWLJSC", "TJNY", "XN", "XQ", "XXPJZ"],
            "hybrid",
            influence_direction="neutral",
            aggregation="gap",
            evidence_label="相对学校平均值偏差",
        ),
    ],
    "daily_routine_boundary": [
        _rule(
            "daily_routine_boundary",
            "first_daily_access_time_avg",
            "首次进出平均时间",
            ["LOGINTIME", "LOGINSIGN"],
            "hybrid",
            influence_direction="negative",
            aggregation="mean",
            evidence_label="首次进出平均时间",
        ),
        _rule(
            "daily_routine_boundary",
            "first_daily_access_time_std",
            "时间波动",
            ["LOGINTIME", "LOGINSIGN"],
            "hybrid",
            influence_direction="negative",
            aggregation="std",
            evidence_label="时间波动",
        ),
        _rule(
            "daily_routine_boundary",
            "late_return_count",
            "晚归次数",
            ["LOGINTIME", "LOGINSIGN"],
            "fixed",
            influence_direction="negative",
            aggregation="count",
            evidence_label="晚归次数",
        ),
        _rule(
            "daily_routine_boundary",
            "late_return_ratio",
            "晚归比例",
            ["LOGINTIME", "LOGINSIGN"],
            "fixed",
            influence_direction="negative",
            aggregation="ratio",
            evidence_label="晚归比例",
        ),
        _rule(
            "daily_routine_boundary",
            "daily_access_time_variability",
            "日内作息波动",
            ["LOGINTIME"],
            "quantile",
            influence_direction="negative",
            aggregation="range",
            evidence_label="日内作息波动",
        ),
    ],
    "physical_resilience": [
        _rule(
            "physical_resilience",
            "physical_test_avg_score",
            "体测均分",
            ["ZF", "TCNF"],
            "fixed",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="体测均分",
        ),
        _rule(
            "physical_resilience",
            "physical_test_pass_flag",
            "是否达标",
            ["ZF"],
            "fixed",
            influence_direction="positive",
            aggregation="flag",
            evidence_label="是否达标",
        ),
        _rule(
            "physical_resilience",
            "weekly_running_count_avg",
            "周均跑步次数",
            ["PUNCH_DAY", "WEEKNUM"],
            "quantile",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="周均跑步次数",
            deferred_status={
                "state": "caveated",
                "condition": "usernum_to_student_id_crosswalk_required",
                "fallback": "direct_physical_metrics_only",
            },
        ),
        _rule(
            "physical_resilience",
            "weekly_exercise_count_avg",
            "周均锻炼次数",
            ["DKCS", "ZC", "XQ"],
            "quantile",
            influence_direction="positive",
            aggregation="mean",
            evidence_label="周均锻炼次数",
        ),
    ],
    "appraisal_status_alert": [
        _rule(
            "appraisal_status_alert",
            "scholarship_amount_sum",
            "奖学金金额",
            ["FFJE"],
            "fixed",
            influence_direction="positive",
            aggregation="sum",
            evidence_label="奖学金金额",
        ),
        _rule(
            "appraisal_status_alert",
            "scholarship_level_score",
            "奖学金等级",
            ["PDDJ", "JLJB"],
            "fixed",
            influence_direction="positive",
            aggregation="max",
            evidence_label="奖学金等级",
        ),
        _rule(
            "appraisal_status_alert",
            "negative_status_alert_flag",
            "是否存在异动预警",
            ["SFZX", "YDLBDM", "YDYYDM"],
            "fixed",
            influence_direction="negative",
            aggregation="flag",
            evidence_label="是否存在异动预警",
        ),
        _rule(
            "appraisal_status_alert",
            "status_change_count",
            "异动次数",
            ["YDLBDM", "YDYYDM", "YDRQ"],
            "fixed",
            influence_direction="negative",
            aggregation="count",
            evidence_label="异动次数",
        ),
    ],
}


def _display_metadata(dimension: str) -> dict[str, object]:
    rules = METRIC_RULE_DECLARATIONS[dimension]
    return {
        "dimension_label": DIMENSION_LABELS[dimension],
        "metric_labels": [rule["display_name"] for rule in rules],
        "metric_names": [rule["metric"] for rule in rules],
        "metric_evidence_labels": [rule["evidence_label"] for rule in rules],
        "metric_aggregations": [rule["aggregation"] for rule in rules],
        "metric_directions": [rule["influence_direction"] for rule in rules],
        "level_labels": LEVEL_LABELS,
        "threshold_strategies": [rule["threshold_strategy"] for rule in rules],
        "support_metric_labels": [
            rule["display_name"] for rule in rules if rule.get("evidence_role") == "support"
        ],
    }


METRIC_DISPLAY_METADATA = {
    dimension: _display_metadata(dimension) for dimension in CALIBRATED_DIMENSIONS
}
