create table if not exists student_term_features (
  student_id text not null,
  term_key text not null,
  major_name text,
  college_name text,
  avg_course_score numeric(6, 2),
  failed_course_count integer,
  avg_gpa numeric(4, 2),
  major_rank_pct numeric(6, 2),
  risk_label text,
  attendance_record_count integer,
  attendance_normal_rate numeric(6, 4),
  selected_course_count integer,
  sign_event_count integer,
  assignment_submit_count integer,
  exam_submit_count integer,
  task_participation_rate numeric(6, 4),
  discussion_reply_count integer,
  library_visit_count integer,
  library_active_days integer,
  running_punch_count integer,
  morning_activity_rate numeric(6, 4),
  primary key (student_id, term_key)
);
